/**
 * Emits the blueprint seed migration from the canonical catalogue, so the SQL and
 * the live seeder can never drift from one another.
 *
 *   bun run scripts/generate-blueprint-seed.ts
 */
import { writeFileSync } from "node:fs";
import { BLUEPRINT_CATALOGUE, validateCatalogue } from "./blueprint-catalogue";

const problems = validateCatalogue(BLUEPRINT_CATALOGUE);
if (problems.length) {
  console.error("Catalogue is invalid:\n" + problems.join("\n"));
  process.exit(1);
}

const sqlString = (value: string) => `'${value.replace(/'/g, "''")}'`;

const rows = BLUEPRINT_CATALOGUE.map((bp) => {
  const config = {
    id: bp.id,
    category: bp.category,
    badge: bp.badge,
    title: bp.title,
    description: bp.description,
    defaultDurationValue: bp.defaultDurationValue,
    defaultDurationUnit: bp.defaultDurationUnit,
    suggestedRoles: bp.suggestedRoles,
    techStack: bp.techStack,
  };
  return `  (${sqlString(bp.id)}, ${sqlString(JSON.stringify(config))}::jsonb)`;
}).join(",\n");

const sql = `-- Scope Blueprint catalogue — generated by scripts/generate-blueprint-seed.ts.
-- Do not edit by hand: change scripts/blueprint-catalogue.ts and regenerate.
--
-- Blueprints move out of the application bundle and into the database. A row with
-- company_id IS NULL is a shared master template; a row with a company_id is that
-- workspace's own copy, which overrides the master of the same id. The app reads
-- both and never carries template content in code.

-- company_id must accept NULL so a master template can exist outside any tenant.
ALTER TABLE public.project_presets ALTER COLUMN company_id DROP NOT NULL;

-- The old primary key cannot span a nullable column.
ALTER TABLE public.project_presets DROP CONSTRAINT IF EXISTS project_presets_pkey;

-- Postgres treats NULLs as distinct in a UNIQUE index, so master rows need their
-- own partial index to stay unique by id.
CREATE UNIQUE INDEX IF NOT EXISTS project_presets_tenant_key
  ON public.project_presets (company_id, id)
  WHERE company_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS project_presets_master_key
  ON public.project_presets (id)
  WHERE company_id IS NULL;

-- Master templates are readable by every authenticated user and writable by none.
DROP POLICY IF EXISTS project_presets_select ON public.project_presets;
CREATE POLICY project_presets_select ON public.project_presets
  FOR SELECT TO authenticated
  USING (company_id IS NULL OR company_id = public.current_company_id());

INSERT INTO public.project_presets (company_id, id, config)
VALUES
${rows
  .split("\n")
  .map((line) => line.replace(/^ {2}\(/, "  (NULL, "))
  .join("\n")}
ON CONFLICT (id) WHERE company_id IS NULL
DO UPDATE SET config = EXCLUDED.config, updated_at = now();
`;

const target = "supabase/migrations/20260913120000_blueprint_catalogue.sql";
writeFileSync(target, sql);
console.log(`Wrote ${target} with ${BLUEPRINT_CATALOGUE.length} blueprints.`);
