// ─── Project preset configurations ──────────────────────────────────────────
import * as React from "react";
import {
  Smartphone,
  Globe,
  Database,
  Palette,
  Briefcase,
  Sliders,
  ShoppingBag,
  Image,
  FileCode,
  Rocket,
} from "lucide-react";
import type { PresetConfig } from "./types";

export const PRESETS: PresetConfig[] = [
  {
    id: "mvp",
    category: "Startups & Custom",
    badge: "Startup MVP",
    title: "Startup MVP (Fast-Track)",
    description:
      "Rapid prototype-to-market build: core validation features, user auth, database & launch in 4-6 weeks.",
    icon: <Rocket className="size-5 text-amber-500" />,
    defaultDurationValue: 4,
    defaultDurationUnit: "weeks",
    suggestedRoles: [
      {
        nameSubstr: "Muhammad Yousuf",
        label: "Team Lead & Architecture",
        allocationPct: 30,
      },
      {
        nameSubstr: "Hassnain",
        label: "Fullstack Developer (MERN)",
        allocationPct: 100,
      },
      {
        nameSubstr: "Yousuf Ansari",
        label: "UI/UX Designer",
        allocationPct: 50,
      },
      { nameSubstr: "Syed Sultan", label: "Project Manager", allocationPct: 25 },
      { nameSubstr: "Kamran faiz", label: "QA Specialist", allocationPct: 30 },
    ],
    techStack: [
      {
        id: "st-mvp-1",
        tech: "React & Next.js",
        category: "frontend",
        suggestedEmployeeSubstr: "Hassnain",
        roleLabel: "Frontend Web Application Lead",
        allocationPct: 100,
      },
      {
        id: "st-mvp-2",
        tech: "Node.js & Express API",
        category: "backend",
        suggestedEmployeeSubstr: "Hassnain",
        roleLabel: "REST API & Serverless Backend",
        allocationPct: 80,
      },
      {
        id: "st-mvp-3",
        tech: "MongoDB Cloud",
        category: "database",
        suggestedEmployeeSubstr: "Hassnain",
        roleLabel: "Document Schema & Aggregations",
        allocationPct: 40,
      },
      {
        id: "st-mvp-4",
        tech: "Figma UI/UX & Wireframes",
        category: "design",
        suggestedEmployeeSubstr: "Yousuf Ansari",
        roleLabel: "Product Wireframes & Interactive UI",
        allocationPct: 50,
      },
      {
        id: "st-mvp-5",
        tech: "DevOps & Cloud Architecture",
        category: "devops",
        suggestedEmployeeSubstr: "Muhammad Yousuf",
        roleLabel: "System Architecture & CI/CD Pipeline",
        allocationPct: 30,
      },
      {
        id: "st-mvp-6",
        tech: "QA & Integration Testing",
        category: "qa",
        suggestedEmployeeSubstr: "Kamran faiz",
        roleLabel: "End-to-End Bug Testing & Validation",
        allocationPct: 30,
      },
      {
        id: "st-mvp-7",
        tech: "Agile Sprint Delivery",
        category: "management",
        suggestedEmployeeSubstr: "Syed Sultan",
        roleLabel: "Scrum Master & Client Alignment",
        allocationPct: 25,
      },
    ],
  },
  {
    id: "mobile_mern",
    category: "Mobile & Backend",
    badge: "Mobile + Node",
    title: "Mobile App (MERN Stack Backend)",
    description:
      "Cross-platform iOS & Android app (Flutter/React Native) with Node.js, Express, MongoDB REST API & real-time sync.",
    icon: <Smartphone className="size-5 text-indigo-500" />,
    defaultDurationValue: 2,
    defaultDurationUnit: "months",
    suggestedRoles: [
      {
        nameSubstr: "Mubashir",
        label: "Mobile App Developer (Flutter/React Native)",
        allocationPct: 100,
      },
      {
        nameSubstr: "Hassnain",
        label: "MERN Backend API Dev",
        allocationPct: 80,
      },
      {
        nameSubstr: "Yousuf Ansari",
        label: "UI/UX Designer",
        allocationPct: 50,
      },
      {
        nameSubstr: "Muhammad Yousuf",
        label: "Team Lead & Architecture",
        allocationPct: 30,
      },
      { nameSubstr: "Syed Sultan", label: "Project Manager", allocationPct: 25 },
      {
        nameSubstr: "Kamran faiz",
        label: "QA & Mobile Testing",
        allocationPct: 40,
      },
    ],
    techStack: [
      {
        id: "st-mmern-1",
        tech: "Flutter / React Native",
        category: "mobile",
        suggestedEmployeeSubstr: "Mubashir",
        roleLabel: "iOS & Android Cross-Platform Lead",
        allocationPct: 100,
      },
      {
        id: "st-mmern-2",
        tech: "Node.js & Express REST API",
        category: "backend",
        suggestedEmployeeSubstr: "Hassnain",
        roleLabel: "Microservices & JWT Auth API",
        allocationPct: 80,
      },
      {
        id: "st-mmern-3",
        tech: "MongoDB Atlas",
        category: "database",
        suggestedEmployeeSubstr: "Hassnain",
        roleLabel: "NoSQL Modeling & Real-Time Sync",
        allocationPct: 40,
      },
      {
        id: "st-mmern-4",
        tech: "Mobile UI/UX Design (Figma)",
        category: "design",
        suggestedEmployeeSubstr: "Yousuf Ansari",
        roleLabel: "iOS & Android HIG/Material Design",
        allocationPct: 50,
      },
      {
        id: "st-mmern-5",
        tech: "Cloud DevOps & Architecture",
        category: "devops",
        suggestedEmployeeSubstr: "Muhammad Yousuf",
        roleLabel: "Backend Hosting & App Store Prep",
        allocationPct: 30,
      },
      {
        id: "st-mmern-6",
        tech: "Mobile Device QA & Regression",
        category: "qa",
        suggestedEmployeeSubstr: "Kamran faiz",
        roleLabel: "Cross-Device Testing & TestFlight QA",
        allocationPct: 40,
      },
      {
        id: "st-mmern-7",
        tech: "Sprint Management",
        category: "management",
        suggestedEmployeeSubstr: "Syed Sultan",
        roleLabel: "Sprint Delivery & Milestone Tracking",
        allocationPct: 25,
      },
    ],
  },
  {
    id: "mobile_laravel",
    category: "Mobile & Backend",
    badge: "Mobile + PHP",
    title: "Mobile App (Laravel Backend)",
    description:
      "Cross-platform iOS & Android app (Flutter/React Native) with PHP Laravel REST API, MySQL & backoffice admin portal.",
    icon: <Smartphone className="size-5 text-rose-500" />,
    defaultDurationValue: 2,
    defaultDurationUnit: "months",
    suggestedRoles: [
      {
        nameSubstr: "Mubashir",
        label: "Mobile App Developer (Flutter/React Native)",
        allocationPct: 100,
      },
      {
        nameSubstr: "Osama khan",
        label: "Laravel API Developer",
        allocationPct: 80,
      },
      {
        nameSubstr: "Yousuf Ansari",
        label: "UI/UX Designer",
        allocationPct: 50,
      },
      {
        nameSubstr: "Muhammad Yousuf",
        label: "Team Lead & Architecture",
        allocationPct: 30,
      },
      { nameSubstr: "Syed Sultan", label: "Project Manager", allocationPct: 25 },
      {
        nameSubstr: "Kamran faiz",
        label: "QA & Mobile Testing",
        allocationPct: 40,
      },
    ],
    techStack: [
      {
        id: "st-mlar-1",
        tech: "Flutter / React Native",
        category: "mobile",
        suggestedEmployeeSubstr: "Mubashir",
        roleLabel: "Cross-Platform Mobile Developer",
        allocationPct: 100,
      },
      {
        id: "st-mlar-2",
        tech: "PHP Laravel REST API",
        category: "backend",
        suggestedEmployeeSubstr: "Osama khan",
        roleLabel: "Laravel Sanctum API & Admin Portal",
        allocationPct: 80,
      },
      {
        id: "st-mlar-3",
        tech: "MySQL Relational Schema",
        category: "database",
        suggestedEmployeeSubstr: "Osama khan",
        roleLabel: "Relational Schema & Migrations",
        allocationPct: 40,
      },
      {
        id: "st-mlar-4",
        tech: "Mobile UI/UX Design (Figma)",
        category: "design",
        suggestedEmployeeSubstr: "Yousuf Ansari",
        roleLabel: "App Flows & Interactive Prototypes",
        allocationPct: 50,
      },
      {
        id: "st-mlar-5",
        tech: "Solutions Architecture & Lead",
        category: "devops",
        suggestedEmployeeSubstr: "Muhammad Yousuf",
        roleLabel: "Architecture Governance & CI/CD",
        allocationPct: 30,
      },
      {
        id: "st-mlar-6",
        tech: "QA & Mobile Testing",
        category: "qa",
        suggestedEmployeeSubstr: "Kamran faiz",
        roleLabel: "Device Compatibility & API Testing",
        allocationPct: 40,
      },
      {
        id: "st-mlar-7",
        tech: "Delivery Governance",
        category: "management",
        suggestedEmployeeSubstr: "Syed Sultan",
        roleLabel: "Project Manager & Sprint Lead",
        allocationPct: 25,
      },
    ],
  },
  {
    id: "social_creatives",
    category: "Design & Creatives",
    badge: "Social & Ads",
    title: "Social Media Post Design & Creatives",
    description:
      "High-converting social media creatives, Instagram/LinkedIn carousels, ad banners & brand marketing assets.",
    icon: <Image className="size-5 text-pink-500" />,
    defaultDurationValue: 3,
    defaultDurationUnit: "weeks",
    suggestedRoles: [
      {
        nameSubstr: "Faiza Jamal",
        label: "Design Lead & Art Direction",
        allocationPct: 60,
      },
      {
        nameSubstr: "Yousuf Ansari",
        label: "Graphic & UI Designer",
        allocationPct: 100,
      },
    ],
    techStack: [
      {
        id: "st-soc-1",
        tech: "Art Direction & Campaign Strategy",
        category: "design",
        suggestedEmployeeSubstr: "Faiza Jamal",
        roleLabel: "Art Director & Brand Strategist",
        allocationPct: 60,
      },
      {
        id: "st-soc-2",
        tech: "Figma Social & Ad Creatives",
        category: "design",
        suggestedEmployeeSubstr: "Yousuf Ansari",
        roleLabel: "High-Res Carousel & Banner Designer",
        allocationPct: 100,
      },
      {
        id: "st-soc-3",
        tech: "Client Pitch & Brand Alignment",
        category: "management",
        suggestedEmployeeSubstr: "Ayesha badar",
        roleLabel: "Client Pitching & Marketing Strategy",
        allocationPct: 20,
      },
    ],
  },
  {
    id: "web_design",
    category: "Design & Creatives",
    badge: "UI/UX Design",
    title: "Web Design (UI/UX & Landing Page)",
    description:
      "Figma high-fidelity responsive website design, design system tokens, interactive prototypes & UX wireframes.",
    icon: <Palette className="size-5 text-purple-500" />,
    defaultDurationValue: 3,
    defaultDurationUnit: "weeks",
    suggestedRoles: [
      {
        nameSubstr: "Faiza Jamal",
        label: "Design Lead & UX Strategy",
        allocationPct: 60,
      },
      {
        nameSubstr: "Yousuf Ansari",
        label: "UI/UX Designer",
        allocationPct: 100,
      },
      {
        nameSubstr: "Kanza Batool",
        label: "Frontend Layout Review",
        allocationPct: 30,
      },
    ],
    techStack: [
      {
        id: "st-wdes-1",
        tech: "UX Research & Design Systems",
        category: "design",
        suggestedEmployeeSubstr: "Faiza Jamal",
        roleLabel: "Design Lead & Token Architect",
        allocationPct: 60,
      },
      {
        id: "st-wdes-2",
        tech: "Figma Responsive UI & Prototypes",
        category: "design",
        suggestedEmployeeSubstr: "Yousuf Ansari",
        roleLabel: "Landing Page & Web App UI Designer",
        allocationPct: 100,
      },
      {
        id: "st-wdes-3",
        tech: "HTML/CSS Styling & Layout Audit",
        category: "frontend",
        suggestedEmployeeSubstr: "Kanza Batool",
        roleLabel: "Frontend Feasibility & Styling Review",
        allocationPct: 30,
      },
    ],
  },
  {
    id: "wordpress",
    category: "CMS & E-Commerce",
    badge: "WordPress CMS",
    title: "WordPress Website & CMS",
    description:
      "Custom corporate WordPress website, theme customization, plugins, SEO readiness, blog & backoffice editor.",
    icon: <FileCode className="size-5 text-blue-500" />,
    defaultDurationValue: 3,
    defaultDurationUnit: "weeks",
    suggestedRoles: [
      {
        nameSubstr: "Osama khan",
        label: "WordPress & PHP Developer",
        allocationPct: 60,
      },
      {
        nameSubstr: "Abdur Rehman",
        label: "Junior Developer & CMS Setup",
        allocationPct: 100,
      },
      {
        nameSubstr: "Yousuf Ansari",
        label: "UI/UX Layout Designer",
        allocationPct: 40,
      },
      { nameSubstr: "Syed Sultan", label: "Project Manager", allocationPct: 20 },
      {
        nameSubstr: "Kamran faiz",
        label: "QA & Browser Testing",
        allocationPct: 30,
      },
    ],
    techStack: [
      {
        id: "st-wp-1",
        tech: "WordPress & PHP Custom Theme",
        category: "backend",
        suggestedEmployeeSubstr: "Osama khan",
        roleLabel: "Lead WordPress Architecture & Custom PHP",
        allocationPct: 60,
      },
      {
        id: "st-wp-2",
        tech: "CMS Config, Plugins & ACF",
        category: "backend",
        suggestedEmployeeSubstr: "Abdur Rehman",
        roleLabel: "CMS Setup & Content Field Structure",
        allocationPct: 100,
      },
      {
        id: "st-wp-3",
        tech: "WordPress UI/UX Layout (Figma)",
        category: "design",
        suggestedEmployeeSubstr: "Yousuf Ansari",
        roleLabel: "Page Templates & Responsive Layouts",
        allocationPct: 40,
      },
      {
        id: "st-wp-4",
        tech: "Cross-Browser & Responsive QA",
        category: "qa",
        suggestedEmployeeSubstr: "Kamran faiz",
        roleLabel: "Browser Compatibility & Speed Testing",
        allocationPct: 30,
      },
      {
        id: "st-wp-5",
        tech: "Delivery & Client Training",
        category: "management",
        suggestedEmployeeSubstr: "Syed Sultan",
        roleLabel: "Project Manager & CMS Handover",
        allocationPct: 20,
      },
    ],
  },
  {
    id: "shopify",
    category: "CMS & E-Commerce",
    badge: "Shopify E-Com",
    title: "Shopify E-Commerce Store",
    description:
      "Complete Shopify store setup, Liquid theme styling, product catalog, payment gateway & inventory sync.",
    icon: <ShoppingBag className="size-5 text-emerald-600" />,
    defaultDurationValue: 3,
    defaultDurationUnit: "weeks",
    suggestedRoles: [
      {
        nameSubstr: "Hassnain",
        label: "Frontend & Liquid Customization",
        allocationPct: 80,
      },
      {
        nameSubstr: "Yousuf Ansari",
        label: "E-Commerce UI/UX",
        allocationPct: 50,
      },
      {
        nameSubstr: "Kanza Batool",
        label: "Product Catalog & Setup",
        allocationPct: 60,
      },
      { nameSubstr: "Syed Sultan", label: "Project Manager", allocationPct: 20 },
      {
        nameSubstr: "Kamran faiz",
        label: "QA & Checkout Testing",
        allocationPct: 30,
      },
    ],
    techStack: [
      {
        id: "st-shp-1",
        tech: "Shopify Liquid & Storefront",
        category: "frontend",
        suggestedEmployeeSubstr: "Hassnain",
        roleLabel: "Liquid Theme Customization & Scripts",
        allocationPct: 80,
      },
      {
        id: "st-shp-2",
        tech: "Product Catalog & App Setup",
        category: "frontend",
        suggestedEmployeeSubstr: "Kanza Batool",
        roleLabel: "Catalog Config & Payment Integrations",
        allocationPct: 60,
      },
      {
        id: "st-shp-3",
        tech: "E-Commerce UI/UX (Figma)",
        category: "design",
        suggestedEmployeeSubstr: "Yousuf Ansari",
        roleLabel: "Cart & High-Converting PDP Design",
        allocationPct: 50,
      },
      {
        id: "st-shp-4",
        tech: "Checkout & Payment QA",
        category: "qa",
        suggestedEmployeeSubstr: "Kamran faiz",
        roleLabel: "Payment Gateway & Cart QA Specialist",
        allocationPct: 30,
      },
      {
        id: "st-shp-5",
        tech: "Launch Management",
        category: "management",
        suggestedEmployeeSubstr: "Syed Sultan",
        roleLabel: "Project Manager & Domain Setup",
        allocationPct: 20,
      },
    ],
  },
  {
    id: "mern",
    category: "Mobile & Backend",
    badge: "MERN SaaS",
    title: "MERN Stack Web App / SaaS",
    description:
      "Full-stack cloud application built with React, Node.js, Express, and MongoDB cloud infrastructure.",
    icon: <Globe className="size-5 text-emerald-500" />,
    defaultDurationValue: 2,
    defaultDurationUnit: "months",
    suggestedRoles: [
      {
        nameSubstr: "Hassnain",
        label: "MERN Stack Developer",
        allocationPct: 100,
      },
      {
        nameSubstr: "Faiza Jamal",
        label: "Design Lead & Prototyping",
        allocationPct: 40,
      },
      { nameSubstr: "Syed Sultan", label: "Project Manager", allocationPct: 25 },
      {
        nameSubstr: "Kanza Batool",
        label: "Junior Frontend Developer",
        allocationPct: 50,
      },
      {
        nameSubstr: "Kamran faiz",
        label: "QA & Integration Testing",
        allocationPct: 30,
      },
    ],
    techStack: [
      {
        id: "st-mern-1",
        tech: "React & TypeScript Frontend",
        category: "frontend",
        suggestedEmployeeSubstr: "Hassnain",
        roleLabel: "Lead React & SPA Web Engineer",
        allocationPct: 100,
      },
      {
        id: "st-mern-2",
        tech: "Node.js & Express REST API",
        category: "backend",
        suggestedEmployeeSubstr: "Hassnain",
        roleLabel: "Node.js Backend & Auth Architecture",
        allocationPct: 80,
      },
      {
        id: "st-mern-3",
        tech: "MongoDB Cloud Atlas",
        category: "database",
        suggestedEmployeeSubstr: "Syed Minhaj",
        roleLabel: "Database Engineer & Indexing",
        allocationPct: 40,
      },
      {
        id: "st-mern-4",
        tech: "SaaS Design System (Figma)",
        category: "design",
        suggestedEmployeeSubstr: "Faiza Jamal",
        roleLabel: "SaaS Design Lead & Component Tokens",
        allocationPct: 40,
      },
      {
        id: "st-mern-5",
        tech: "Tailwind UI Components",
        category: "frontend",
        suggestedEmployeeSubstr: "Kanza Batool",
        roleLabel: "Junior Frontend & Styling",
        allocationPct: 50,
      },
      {
        id: "st-mern-6",
        tech: "API & E2E Test Automation",
        category: "qa",
        suggestedEmployeeSubstr: "Kamran faiz",
        roleLabel: "End-to-End Test Specialist",
        allocationPct: 30,
      },
      {
        id: "st-mern-7",
        tech: "Agile Scrum Delivery",
        category: "management",
        suggestedEmployeeSubstr: "Syed Sultan",
        roleLabel: "Scrum Master & Delivery Lead",
        allocationPct: 25,
      },
    ],
  },
  {
    id: "laravel",
    category: "Mobile & Backend",
    badge: "Laravel Web",
    title: "Laravel Web Application & Portal",
    description:
      "Enterprise PHP/Laravel web portal, relational MySQL schema, authentication, roles & backoffice dashboard.",
    icon: <Database className="size-5 text-red-500" />,
    defaultDurationValue: 6,
    defaultDurationUnit: "weeks",
    suggestedRoles: [
      {
        nameSubstr: "Osama khan",
        label: "Laravel Developer",
        allocationPct: 100,
      },
      {
        nameSubstr: "Muhammad Yousuf",
        label: "Team Lead & Architecture",
        allocationPct: 30,
      },
      {
        nameSubstr: "Yousuf Ansari",
        label: "UI/UX Designer",
        allocationPct: 40,
      },
      {
        nameSubstr: "Abdur Rehman",
        label: "Junior Backend Developer",
        allocationPct: 50,
      },
      { nameSubstr: "Syed Sultan", label: "Project Manager", allocationPct: 25 },
    ],
    techStack: [
      {
        id: "st-lar-1",
        tech: "PHP Laravel 11 Framework",
        category: "backend",
        suggestedEmployeeSubstr: "Osama khan",
        roleLabel: "Senior Laravel Portal Developer",
        allocationPct: 100,
      },
      {
        id: "st-lar-2",
        tech: "MySQL Relational Schema",
        category: "database",
        suggestedEmployeeSubstr: "Osama khan",
        roleLabel: "Relational Modeling & Query Optimization",
        allocationPct: 50,
      },
      {
        id: "st-lar-3",
        tech: "Backoffice Admin Dashboard",
        category: "backend",
        suggestedEmployeeSubstr: "Abdur Rehman",
        roleLabel: "Junior Backend & CRUD Integration",
        allocationPct: 50,
      },
      {
        id: "st-lar-4",
        tech: "Dashboard UI/UX (Figma)",
        category: "design",
        suggestedEmployeeSubstr: "Yousuf Ansari",
        roleLabel: "Admin Dashboard & Portal UX",
        allocationPct: 40,
      },
      {
        id: "st-lar-5",
        tech: "Enterprise Architecture Review",
        category: "devops",
        suggestedEmployeeSubstr: "Muhammad Yousuf",
        roleLabel: "Principal Architect & Code Review",
        allocationPct: 30,
      },
      {
        id: "st-lar-6",
        tech: "Sprint Delivery & Client Demo",
        category: "management",
        suggestedEmployeeSubstr: "Syed Sultan",
        roleLabel: "Project Manager",
        allocationPct: 25,
      },
    ],
  },
  {
    id: "enterprise",
    category: "Startups & Custom",
    badge: "Enterprise Suite",
    title: "Enterprise Custom Software Suite",
    description:
      "End-to-end multi-platform squad with mobile apps, web platform, cloud API, QA lead & Director strategic advisory.",
    icon: <Briefcase className="size-5 text-blue-600" />,
    defaultDurationValue: 3,
    defaultDurationUnit: "months",
    suggestedRoles: [
      {
        nameSubstr: "Muhammad Yousuf",
        label: "Team Lead & Solutions Architect",
        allocationPct: 60,
      },
      {
        nameSubstr: "Hassnain",
        label: "MERN Fullstack Developer",
        allocationPct: 100,
      },
      {
        nameSubstr: "Osama khan",
        label: "Laravel & Backend Developer",
        allocationPct: 100,
      },
      {
        nameSubstr: "Mubashir",
        label: "Mobile App Developer",
        allocationPct: 100,
      },
      { nameSubstr: "Faiza Jamal", label: "Design Lead", allocationPct: 50 },
      {
        nameSubstr: "Syed Sultan",
        label: "Project Manager",
        allocationPct: 40,
      },
      {
        nameSubstr: "Omair",
        label: "Director Strategy & Enterprise Review",
        allocationPct: 10,
      },
      { nameSubstr: "Kamran faiz", label: "QA Lead", allocationPct: 50 },
    ],
    techStack: [
      {
        id: "st-ent-1",
        tech: "Flutter / iOS & Android",
        category: "mobile",
        suggestedEmployeeSubstr: "Mubashir",
        roleLabel: "Senior Mobile Engineer",
        allocationPct: 100,
      },
      {
        id: "st-ent-2",
        tech: "React & Next.js Web App",
        category: "frontend",
        suggestedEmployeeSubstr: "Hassnain",
        roleLabel: "Lead Frontend Engineer",
        allocationPct: 100,
      },
      {
        id: "st-ent-3",
        tech: "Laravel Microservices API",
        category: "backend",
        suggestedEmployeeSubstr: "Osama khan",
        roleLabel: "Senior Backend Engineer",
        allocationPct: 100,
      },
      {
        id: "st-ent-4",
        tech: "Enterprise Solutions Architecture",
        category: "devops",
        suggestedEmployeeSubstr: "Muhammad Yousuf",
        roleLabel: "Principal Solutions Architect",
        allocationPct: 60,
      },
      {
        id: "st-ent-5",
        tech: "Enterprise Design System (Figma)",
        category: "design",
        suggestedEmployeeSubstr: "Faiza Jamal",
        roleLabel: "Design Lead & Token Architect",
        allocationPct: 50,
      },
      {
        id: "st-ent-6",
        tech: "Enterprise QA & Automation",
        category: "qa",
        suggestedEmployeeSubstr: "Kamran faiz",
        roleLabel: "QA Lead & Security Testing",
        allocationPct: 50,
      },
      {
        id: "st-ent-7",
        tech: "Agile Program Management",
        category: "management",
        suggestedEmployeeSubstr: "Syed Sultan",
        roleLabel: "Technical Program Manager",
        allocationPct: 40,
      },
      {
        id: "st-ent-8",
        tech: "Executive Advisory & Governance",
        category: "management",
        suggestedEmployeeSubstr: "Omair",
        roleLabel: "Director Technology Strategy",
        allocationPct: 10,
      },
    ],
  },
  {
    id: "custom",
    category: "Startups & Custom",
    badge: "Custom Scope",
    title: "Custom Fast Estimate",
    description:
      "Build a customized query by choosing exact team members, allocation percentages, and timeline.",
    icon: <Sliders className="size-5 text-amber-500" />,
    defaultDurationValue: 1,
    defaultDurationUnit: "months",
    suggestedRoles: [],
    techStack: [
      {
        id: "st-cust-1",
        tech: "React / Modern Frontend",
        category: "frontend",
        suggestedEmployeeSubstr: "Hassnain",
        roleLabel: "Frontend Engineer",
        allocationPct: 50,
      },
      {
        id: "st-cust-2",
        tech: "Node.js / Laravel Backend",
        category: "backend",
        suggestedEmployeeSubstr: "Osama khan",
        roleLabel: "Backend Engineer",
        allocationPct: 50,
      },
      {
        id: "st-cust-3",
        tech: "Figma UI/UX Prototyping",
        category: "design",
        suggestedEmployeeSubstr: "Yousuf Ansari",
        roleLabel: "UI/UX Designer",
        allocationPct: 30,
      },
    ],
  },
];
